### ISSUE TITLE
A. Another (smaller) CKAN Upgrade

### ISSUE THREAD

**Issue by jrdh** [NaturalHistoryMuseum/dataportal-docs#18]
## Overview
At the end of 2019, Python 2 was [deprecated](https://www.python.org/doc/sunset-python-2/). The Data Portal is built on CKAN which is a library that depends on Python 2. Although there has been significant development to upgrade CKAN to use Python 3 by the core CKAN developers, a Python 3 compatible release is still not available yet as of July 2020. 

As soon as a Python 3 compatible release is available (expected to be CKAN 2.9) we will begin upgrading our source code to work with it and Python 3. It is expected that CKAN 2.9 will be released by the end of July 2020 ([track](https://github.com/ckan/ckan/issues/5485)). 

Upgrading the Data Portal to work with Python 3 and a Python 3 compatible CKAN version is crucial to ensure we maintain good security standards and can continue to maintain the Data Portal in the future, however, it will also allow the use of the latest tools and libraries for Python and should come with a small performance boost. 

It is expected that this work will be significant but much less laborious when compared to the previous CKAN upgrade from 2.3 to 2.8. 

## Tasks
- [x] Upgrade CKAN to 2.9 
- [x] Upgrade dev, staging and production installations to Python 3 
- [x] Upgrade all our custom extensions to be compatible with Python 3

**Comment by jrdh** [comment]
Tasks:

- [x] Upgrade our CKAN fork to CKAN 2.9.1 (but still running on python 2.7) - https://github.com/NaturalHistoryMuseum/ckan/pull/5
- [x] Update all extensions to work with CKAN 2.9 on python 2.7
  - [x] ckanext-ckanpackager
  - [x] ckanext-contact
  - [x] ckanext-dcat
  - [x] ckanext-doi
  - [x] ckanext-gallery
  - [x] ckanext-gbif
  - [x] ckanext-graph
  - [x] ckanext-iiif
  - [x] ckanext-ldap
  - [x] ckanext-list
  - [x] ckanext-nhm
  - [x] ckanext-pdfview [currently using https://github.com/DataShades/ckanext-pdfview/tree/py3 which is waiting to be merged into the main ckan-pdfview repo/be moved into the main ckan repo]
  - [x] ckanext-query-dois
  - [x] ckanext-sketchfab
  - [x] ckanext-spatial
  - [x] ckanext-statistics
  - [x] ckanext-status
  - [x] ckanext-twitter
  - [x] ckanext-userdatasets
  - [x] ckanext-versioned-datastore
  - [x] ckanext-versioned-tiledmap
  - [x] ckanext-video
  - [x] ckanext-viewhelpers [deleted as no longer needed]
- [x] Update all extensions to work with CKAN 2.9 on python 3.8
  - [x] ckanext-ckanpackager
  - [x] ckanext-contact
  - [x] ckanext-dcat
  - [x] ckanext-doi
  - [x] ckanext-gallery
  - [x] ckanext-gbif
  - [x] ckanext-graph
  - [x] ckanext-iiif
  - [x] ckanext-ldap
  - [x] ckanext-list
  - [x] ckanext-nhm
  - [x] ckanext-pdfview
  - [x] ckanext-query-dois
  - [x] ckanext-sketchfab
  - [x] ckanext-spatial
  - [x] ckanext-statistics
  - [x] ckanext-status
  - [x] ckanext-twitter
  - [x] ckanext-userdatasets
  - [x] ckanext-versioned-datastore
  - [x] ckanext-versioned-tiledmap
  - [x] ckanext-video
  - [x] ckanext-viewhelpers
- [x] Update old nosetests based tests to work on pytest and update CI infrastrucutre for all extensions
  - [x] ckanext-ckanpackager
  - [x] ckanext-contact
  - [x] ckanext-dcat
  - [x] ckanext-doi
  - [x] ckanext-gallery
  - [x] ckanext-gbif
  - [x] ckanext-graph
  - [x] ckanext-iiif
  - [x] ckanext-ldap
  - [x] ckanext-list
  - [x] ckanext-nhm
  - [x] ckanext-pdfview
  - [x] ckanext-query-dois
  - [x] ckanext-sketchfab
  - [x] ckanext-spatial
  - [x] ckanext-statistics
  - [x] ckanext-status
  - [x] ckanext-twitter
  - [x] ckanext-userdatasets
  - [x] ckanext-versioned-datastore
  - [x] ckanext-versioned-tiledmap
  - [x] ckanext-video
  - [x] ckanext-viewhelpers
- [x] update deployment scripts for dev, staging and production
- [x] deploy!
