### ISSUE TITLE
B. Integrated Search Maps

### ISSUE THREAD

**Issue by jrdh** [NaturalHistoryMuseum/dataportal-docs#19]
## Overview
The initial release of the integrated search on the Data Portal only supported the list and grid views of the result data and lacked the map and gallery views made available on the old search pages. The gallery view has recently been reimplemented as part of the integrated search, however, maps have not been. 

Being able to view data on a map is a high priority feature for users and was one of the most popular suggestions on the feedback site during the suggestion collection phase of this roadmap. Adding maps to the integrated search interface also opens new opportunities to render location data from different resources on the same map which gives users a new way to find and link resource data. 

## Tasks
- [ ] Investigate the best way to render the location data from many resources on one map 
- [ ] Extend the integrated search interface to include a map result view 
- [ ] Explore some new functionality ideas in the new map view, such as (note that these may or may not be implemented, these are merely example ideas): 
  - [ ] Different base tile source options, such as satellite and bathymetric 
  - [ ] Point clustering 
  - [ ] Point colouring based on secondary field (e.g. taxon) 
  - [ ] Animated maps showing changes over time 
  - [ ] 3D maps 
- [ ] Explore allowing users to export maps directly from the Data Portal as images 
- [ ] Direct filtering on the map view (geo filters can already be applied elsewhere but it would be beneficial if users could modify these filters directly on the map view)

**Comment by jrdh** [comment]
We should also consider record uncertainty, particularly in light of https://headwayapp.co/nhm-data-portal-changelog/new-specimen-collection-field-coordinateuncertaintyinmeters-170260 but also with respect to the large number of records in EMu that don't have specific points associated with them.
