### ISSUE TITLE
D. WCAG AA Accessibility Standard

### ISSUE THREAD

**Issue by jrdh** [NaturalHistoryMuseum/dataportal-docs#21]
## Overview
In line with the Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018, we need to ensure we meet [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/) AA standard across as much of the NHM’s digital portfolio as possible. As the Data Portal is a part of this digital portfolio, this applies to us too. 

## Tasks 
- [x] Investigate the parts of the WCAG AA standard we currently don’t meet 
- [x] Improve the parts of the Data Portal that fall short of the AA standard

**Comment by jrdh** [comment]
This needs to be completed by 23/09/20.

**Comment by jrdh** [comment]
Areas that need looking at:
- [x] Home page
- [x] Datasets
- [x] Contact
- [x] About
  - [x] Citation and attribution
  - [x] Download and API
  - [x] Site statistics
  - [x] Credits
- [x] Integrated search
- [x] Resource page
  - [x] Edit resource
  - [x] DataStore
  - [x] Views (+ Reorder resource view)
  - [x] New view pages
  - [x] Map view
  - [x] Grid view
  - [x] Image view
  - [x] PDF view
  - [x] Sketchfab view
- [x] New dataset page
- [x] Dataset page
  - [x] Activity stream
  - [x] Edit metadata
  - [x] Resources (+ Reorder resources)
  - [x] Add new resources
- [x] Contact popup
- [x] Download popup
- [x] User page
  - [x] User activity
  - [x] Manage user
- [x] Login page
- [x] Dashboard
  - [x] My datasets
- [x] Admin
  - [x] Sysadmins
  - [x] Config
  - [x] Trash
- [x] Organization page
  - [x] Datasets
  - [x] Activity Stream
  - [x] About
  - [x] Edit
  - [x] Datasets
  - [x] Members
- [x] Add member
- [x] Record page
    - [x] Normal view
    - [x] DwC view
    - [x] GBIF view
    - [x] GBIF data quality indicators
- [x] VFactor IIIF Page
- [x] Groups
    - [x] New group
    - [x] Datasets
    - [x] Activity Stream
    - [x] About
    - [x] Edit
    - [x] Datasets
    - [x] Members
- [x] Status bar

---

- [x] Documentation for WCAG AA dev

**Comment by jrdh** [comment]
Developer documentation on meeting WCAG AA: https://github.com/NaturalHistoryMuseum/data-portal/wiki/Developing-with-WCAG.
