### ISSUE TITLE
E. Link Data Portal and Phenome10K

### ISSUE THREAD

**Issue by jrdh** [NaturalHistoryMuseum/dataportal-docs#22]
## Overview
With the redevelopment of [Phenome10K](https://phenome10k.org/) by the NHM Informatics team we now have an opportunity to create bidirectional linkage between it and the Data Portal. Phenome10K hosts 3D scans of various specimens from the NHM’s collection (and third-party collections too) and by integrating with it we would be able to show Data Portal users 3D scans of specimens if they are available on Phenome10K, enriching the data available to users. Phenome10K would also be able to show additional data about the specimens it hosts scans of using the Data Portal API, such as provide common citation information (i.e. the specimen’s CETAF identifier).

## Tasks
- [ ] Determine the best way to link Phenome10K data into the Data Portal, options include but are not limited to: 
  - [ ] Importing the data into the specimen search index (this allows searching for specimens with Phenome10K links) 
  - [ ] Dynamically finding Phenome10K links on the record pages 
- [ ] Integrate the Data Portal with Phenome10K
