### ISSUE TITLE
I. DOI Overview Page for Datasets and Resources

### ISSUE THREAD

**Issue by jrdh** [NaturalHistoryMuseum/dataportal-docs#26]
## Overview
At present we offer DOIs to users for datasets and queries so that they can cite them. We then use the data about these DOIs to measure the impact, however, we don’t make any of this data available to users directly on the Data Portal. It would be beneficial for users and dataset/resource authors to see the impact of their data on dedicated pages. 

Exactly what information we want to show will need to be determined, however, some possible options include: 
- The number of query DOIs minted against a dataset’s resources/an individual resource 
- Word cloud of terms used in the searches associated with query DOIs 
- Citation tracing using DataCite’s GraphQL API to find publications using the DOIs we’ve minted for a dataset/resources 

## Tasks
- [ ] Determine what information we can show users
- [ ] Determine what information we wish to show users/would be beneficial for users to see
- [ ] Design new pages
- [ ] Implement any new statistics gathering functionality as required
- [ ] Implement new pages
