### ISSUE TITLE
M. Enhanced Download Experience

### ISSUE THREAD

**Issue by jrdh** [NaturalHistoryMuseum/dataportal-docs#30]
## Overview
Downloading data is one of the most important features of the Data Portal, not only from the user's point of view but also as it is the basis for most of our impact metrics. There are a few places where the user’s download experience could be improved which are listed as tasks below.

## Tasks
- [ ] Allow users to choose the fields that are included in their download files  
- [ ] Allow users to choose the order of the fields that are included in their download files 
- [x] Deprecate and remove the CKAN packager mechanism (there are currently two download systems running in the Data Portal ecosystem) 
- [x] Investigate whether sending HTML download emails to users would enable us more control over how eur03.safelinks URLs are rendered 
- [x] Investigate supporting downloads (under specific circumstances) without providing an email address using NGINX X-Accel 
- [x] Investigate the merits and options of implementing a simple pre-download processing system to allow a set of simple modifications to be completed on the data before download (such as automatic data cleaning) 
- [ ] Explore the suitability of different download infrastructure options (Dat, torrents etc), particularly with an eye to supporting bulk image downloads in the future

**Comment by alycejenni** [comment]
Remaining issues have been added as separate tasks on the [portal project board](https://github.com/orgs/NaturalHistoryMuseum/projects/26/views/5)
