### ISSUE TITLE
ORCID Integration

### ISSUE THREAD

**Issue by jrdh** [NaturalHistoryMuseum/dataportal-docs#9]
### Overview
The intent of this work is to provide integration between datasets on the Data Portal and the ORCID identifiers of its authors. This will allow authors to better track their work on the Data Portal from external sites that support ORCID, such as the NHM's install of Symplectic Elements.

#### Required featureset
 - [x] Allow users to associate author ORCID identifiers with datasets
 - [x] Include collected OCRID identifiers in new DOIs
 - [x] Include links to author ORCID identifiers on the dataset page
 - [x] Backfill ORCID identifiers for existing datasets

#### Extended featureset (needs discussion before undertaking)
 - [ ] Request dataset association with your ORCID identifier
 - [ ] Publish datasets to ORCID

**Comment by PaulKiddle** [comment]
Notes for when I'm back:

Update ckan-doi to remove either metadata_to_xml from api.py or plugin.build_metadata from lib.py&plugin.py, and replace xmltodict with [datacite.schema41](https://datacite.readthedocs.io/en/latest/). Update build_metadata to output schema41 input args. Add plugin functions to build creators array (defaults to one author with just a name) - alternatively don't do this, just have other plugins rewrite the creators array in the existing hook function.

In ckanext-doi:
Add author_orcid to logic/schema.py, write/rewrite the creators array in the ckanexd-doi hook, add the orcid field to the form.
Contributors - similar steps but mayhaps a nice set of form controls would be better than entering via a textarea?
